### PR TITLE
Add talk language

### PR DESCRIPTION
**Pull request by abdonrd**
I'm not sure if it is the best option, but it should works.

### CODE REVIEW

**Comment by jorgecasar** [comment]
Taking advantage of the revert. I guess it's better to use [ISO 639-1 codes ](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)

**Comment by abdonrd** [comment]
@jorgecasar like this?

``` js
if (language === 'en') {
  return '🇺🇸 ';
} else if (language === 'es') {
  return '🇪🇸 ';
} else {
  return undefined;
}
```

**Comment by jorgecasar** [comment]
Yes, but I guess uglify doesn't like emjis. Look at the error of the build process on PR #120

**Comment by abdonrd** [comment]
@jorgecasar oops! My fault! It was a syntax error. Solved at https://github.com/polymer-day/web/pull/122

**Pull request merged**
