### PR TITLE
Check if exists shadowRoot to avoid problems in Firefox

### LINKED ISSUE #124: Speakers section: missing styles in Firefox
The speakers section in Firefox is broken.

polymer_day_madrid_21-22_octubre_2016_-_2016-10-05_14 59 57

### PR DESCRIPTION
**Pull request by felixzapata**
Fix #124.

It is a quick fix to avoid problems about the no support of Shadow DOM.

### CODE REVIEW

**Comment by jorgecasar** [comment]
You committed only code style, not the fix

**Comment by felixzapata** [comment]
humm i don´t know why to copy the fix the lines of the styles has changed. I am going to check it.

**Comment by felixzapata** [comment]
The changes of the styles lines have been modify after saving the file with my editor

**Comment by felixzapata** [comment]
I´ve update the pull request (with two commits). In this file, the first time I do a change, the lines of the styles are changed.

**Pull request merged**
