### PR TITLE
feat(polymerday-speaker.html) add anchor element to navigate to speaker

### LINKED ISSUE #95: Speaker anchor name
To navigate to speaker item add an anchor tag with name like the speaker name without spaces

### PR DESCRIPTION
**Pull request by manufosela**
Fix #95

### CODE REVIEW

**Comment by jorgecasar** [comment]
There are a id for each speaker. Show how is done in schedule

**Comment by jorgecasar** [comment]
Reabase, please 🙏

**Comment by manufosela** [comment]
Done! :+1:

**Comment by jorgecasar** [comment]
Ouch! The @beatbits changes break yours 😢

**Comment by reiaguilera** [comment]
pls solve!

**Pull request closed without merging**
